# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: marcoshenriquedev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: calda
# "service" is the name of this project. This will also be added to your AWS resource names.
service: calda

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt CaldaTable.Arn
 # S3
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: !Join ['/', [!GetAtt CaldaBucket.Arn, '*']]
        - Effect: Allow
          Action:
            - s3:DeleteObject
          Resource: !Join ['/', [!GetAtt CaldaBucket.Arn, '*']]
        - Effect: 'Allow'
          Action:
            - 's3:PutBucketAcl'
            - s3:PutBucketPolicy
          Resource:
            - !GetAtt CaldaBucket.Arn

resources:
  Resources:
    CaldaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CaldaTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
  Resources:
    CaldaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: caldaapp-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - DELETE

