org: marcoshenriquedev
app: calda
service: calda

build:
  esbuild:
    minify: true
    target: node20
    sourcemap: false
    exclude:
      - "@aws-sdk/*"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt CaldaTable.Arn
resources:
  Resources:
    CaldaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CaldaTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE

functions:
  createCook:
    handler: src/functions/cooks/createCook.handler
    events:
      - httpApi:
          path: /cooks
          method: POST
